import Head from "next/head";
import { BsCircleHalf } from "react-icons/bs";
import {
	AiFillInstagram,
	AiFillLinkedin,
	AiFillGithub,
	AiOutlineArrowDown,
} from "react-icons/ai";
import Image from "next/image";
import headshot from "../public/images/boe-headshot-circle.png";
import { useState } from "react";
import AboutMe from "../components/AboutMe";
import pennbook from "../public/images/pennbook.png";
import manage from "../public/images/manage.png";
import { Swiper, SwiperSlide } from "swiper/react";
import { Transition } from "@headlessui/react";
import { Navigation, Pagination } from "swiper";
import "swiper/css/bundle";
import { Disclosure } from "@headlessui/react";
import accenture from "../public/images/accenture.png";
import supernow from "../public/images/supernow.avif";
import firstround from "../public/images/firstround.png";
import seaswellness from "../public/images/seas-wellness.png";
import blog from "../public/images/blog.png";

export default function Home() {
	const [darkMode, setDarkMode] = useState(false);
	const [menuOpen, setMenuOpen] = useState(false);
	const [aboutMe, showAboutMe] = useState(false);
	const projectData = [
		{
			title: "Blogging Platform",
			description:
				"In a course I took, I developed a blogging platform very similar to Medium and Dev.to with features such as Google Authentication, custom usernames, real-time CRUD posts and hearts, SEO compatability, and image file uploads.",
			tech: ["React", "Next.js", "Firebase", "CSS Modules"],
			image: blog,
		},
		{
			title: "Social Media Website",
			description:
				"For a class group project, we designed and developed a mock Facebook app with features such as account registration, friend networks, network visualization, dynamic content, real-time chat channels, and news recommendation.",
			tech: [
				"React",
				"Bootstrap",
				"Node",
				"Express",
				"DynamoDB",
				"Socket.io",
				"EC2",
			],
			image: pennbook,
		},
		{
			title: "Team Management App",
			description: "Designed a team management website for a B2B SaaS company.",
			tech: ["React", "Tailwind"],
			image: manage,
		},
	];

	return (
		<div className={darkMode ? "dark" : ""}>
			<Head>
				<title>Ryan De Lopez</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<main className="dark:bg-black px-10 md:px-20 bg-white">
				<section className="min-h-screen">
					{/* Navbar */}
					<nav className="relative container mx-auto p-6">
						{/* Flex Container */}
						<div className="flex justify-between items-center">
							{/* Logo */}
							<a href="#">
								<h1 className="text-xl font-burtons">ryandelopez</h1>
							</a>

							{/* Menu Items */}
							<div className="hidden space-x-12 md:flex justify-between items-center">
								<a
									href="#"
									className="group text-mainBlack font-poppins font-light transition duration-300"
								>
									Projects
									<span class="block max-w-0 group-hover:max-w-full transition-all duration-500 h-0.5 bg-mainBlue"></span>
								</a>
								<button
									className="group text-mainBlack font-poppins font-light transition duration-300"
									onClick={() => showAboutMe(true)}
								>
									Contact
									<span className="block max-w-0 group-hover:max-w-full transition-all duration-500 h-0.5 bg-mainBlue"></span>
								</button>
								{/* Dark Mode Toggle */}
								<div className="group">
									<BsCircleHalf
										className="cursor-pointer text-2xl text-mainBlack font-poppins font-light transition duration-300 mb-1"
										onClick={() => setDarkMode(!darkMode)}
									/>
									<span class="block max-w-0 group-hover:max-w-full transition-all duration-500 h-0.5 bg-mainBlue"></span>
								</div>
								<a
									href={"../public/images/resume.pdf"}
									className="relative inline-flex items-center px-6 py-2 overflow-hidden text-medium font-poppins font-light text-mainBlue border-2 border-mainBlue rounded-full hover:text-white group hover:bg-gray-50"
									target="_blank"
								>
									<span className="overflow-hidden absolute left-0 block w-full h-0 transition-all bg-mainBlue opacity-100 group-hover:h-full top-1/2 group-hover:top-0 duration-400 ease"></span>
									<span className="overflow-hidden absolute right-0 flex items-center justify-start w-10 h-10 duration-300 transform translate-x-full group-hover:translate-x-0 ease"></span>
									<span class="relative">Resume</span>
								</a>
							</div>

							{/* Hamburger Icon */}
							<button
								id="menu-btn"
								className={`${
									menuOpen && "open"
								} block hamburger md:hidden focus:outline-none`}
								onClick={() => setMenuOpen(!menuOpen)}
							>
								<span className="hamburger-top"></span>
								<span className="hamburger-middle"></span>
								<span className="hamburger-bottom"></span>
							</button>
						</div>
						{/* Mobile Menu */}
						<div className="md:hidden">
							<div
								id="menu"
								className={`${
									menuOpen ? "flex" : "hidden"
								} absolute flex-col items-center self-end py-8 mt-10 space-y-6 font-bold bg-white sm:w-auto sm:self-center left-6 right-6 drop-shadow-md`}
							>
								<a href="#" className="">
									Projects
								</a>
								<a href="#" className="">
									Contact
								</a>
							</div>
						</div>
					</nav>
					{/* Hero */}
					<div className="container mx-auto flex flex-row items-center">
						<div className="text-left p-24">
							<h1 className="text-mainBlack font-poppins text-md font-light ">
								Hey! I'm
							</h1>
							<h2 className="text-5xl py-2 text-mainBlack md:text-6xl font-poppins font-extrabold">
								Ryan De Lopez, a
							</h2>
							<h3 className="text-5xl py-2 font-poppins font-extrabold text-mainBlue md:text-6xl">
								Penn Student
							</h3>
							<p className="text-md py-5 leading-8 text-mainGray font-poppins font-light md:text-lg max-w-lg">
								I'm a sophomore studying at the University of Pennsylvania
								aspiring to solve societal problems through technology.
							</p>
							<div className="text-2xl flex justify-start gap-10 pt-0 pb-6 text-maroon">
								<a
									href="https://www.linkedin.com/in/vrdelopez/"
									target="_blank"
									className="hover:text-brightMaroon"
								>
									<AiFillLinkedin />
								</a>
								<a
									href="https://www.instagram.com/ryandelopez/"
									target="_blank"
									className="hover:text-brightMaroon"
								>
									<AiFillInstagram />
								</a>
								<a
									href="https://github.com/rydelopez"
									target="_blank"
									className="hover:text-brightMaroon"
								>
									<AiFillGithub />
								</a>
							</div>
							<button
								className="relative inline-flex items-center px-12 py-3 overflow-hidden text-lg font-poppins font-light text-mainBlue border-2 border-mainBlue rounded-full hover:text-white group hover:bg-gray-50"
								onClick={() => showAboutMe(true)}
							>
								<span className="overflow-hidden absolute left-0 block w-full h-0 transition-all bg-mainBlue opacity-100 group-hover:h-full top-1/2 group-hover:top-0 duration-400 ease"></span>
								<span className="overflow-hidden absolute right-0 flex items-center justify-start w-10 h-10 duration-300 transform translate-x-full group-hover:translate-x-0 ease">
									<svg
										className="w-5 h-5"
										fill="none"
										stroke="currentColor"
										viewBox="0 0 24 24"
										xmlns="http://www.w3.org/2000/svg"
									>
										<path
											stroke-linecap="round"
											stroke-linejoin="round"
											stroke-width="2"
											d="M14 5l7 7m0 0l-7 7m7-7H3"
										></path>
									</svg>
								</span>
								<span class="relative">About Me</span>
							</button>
						</div>
						<div className="relative my-20 mx-auto w-80 h-80">
							<Image src={headshot} />
						</div>
					</div>
					<Transition
						show={aboutMe}
						enter="transition-opacity duration-300"
						enterFrom="opacity-0"
						enterTo="opacity-100"
						leave="transition-opacity duration-0"
						leaveFrom="opacity-100"
						leaveTo="opacity-0"
					>
						<AboutMe open={aboutMe} onClose={() => showAboutMe(false)} />
					</Transition>
				</section>
				<section className="min-h-screen">
					<div className="relative flex py-5 items-center">
						<div className="flex-grow border-t border-gray-400"></div>
						<span className="flex-shrink mx-4 py-10 font-poppins font-extrabold text-mainBlack text-3xl">
							Projects
						</span>
						<div className="flex-grow border-t border-gray-400"></div>
					</div>
					<div className="container flex mx-auto">
						<Swiper
							modules={[Navigation, Pagination]}
							navigation
							pagination={{ clickable: true }}
							effect
							speed={500}
							slidesPerView={1}
							loop
							autoplay={{ delay: 5000 }}
							className="container object-cover"
						>
							{projectData.map((project) => (
								<SwiperSlide className="swiperslide">
									<div className="py-4 flex flex-row items-center">
										<div className="w-auto pl-20 min-w-[50%]">
											<Image src={project.image} />
										</div>
										<div className="flex flex-col items-left w-5/6 p-6 mx-20">
											<h1 className="font-poppins font-extrabold text-mainBlack text-3xl pb-5">
												{project.title}
											</h1>
											<p className="font-poppins font-light text-mainGray text-md md:text-lg">
												{project.description}
											</p>
											<ul className="flex flex-row font-poppins font-bold text-maroon text-sm md:text-md space-x-6 justify-center pt-5 flex-wrap">
												{project.tech.map((tech) => (
													<li>{tech}</li>
												))}
											</ul>
											<div className="relative text-center pt-5">
												<button
													className="relative inline-flex items-center px-12 py-3 overflow-hidden text-lg font-poppins font-light text-mainBlue border-2 border-mainBlue rounded-full hover:text-white group hover:bg-gray-50"
													onClick={() => showAboutMe(true)}
												>
													<span className="overflow-hidden absolute left-0 block w-full h-0 transition-all bg-mainBlue opacity-100 group-hover:h-full top-1/2 group-hover:top-0 duration-400 ease"></span>
													<span className="overflow-hidden absolute right-0 flex items-center justify-start w-10 h-10 duration-300 transform translate-x-full group-hover:translate-x-0 ease">
														<svg
															className="w-5 h-5"
															fill="none"
															stroke="currentColor"
															viewBox="0 0 24 24"
															xmlns="http://www.w3.org/2000/svg"
														>
															<path
																stroke-linecap="round"
																stroke-linejoin="round"
																stroke-width="2"
																d="M14 5l7 7m0 0l-7 7m7-7H3"
															></path>
														</svg>
													</span>
													<span class="relative items-center">
														View on GitHub
													</span>
												</button>
											</div>
										</div>
									</div>
								</SwiperSlide>
							))}
						</Swiper>
					</div>
				</section>
				<section className="min-h-screen">
					<div className="relative flex py-5 items-center">
						<div className="flex-grow border-t border-gray-400"></div>
						<span className="flex-shrink mx-4 py-10 font-poppins font-extrabold text-mainBlack text-3xl">
							Education
						</span>
						<div className="flex-grow border-t border-gray-400"></div>
					</div>
					<div className="container flex flex-row mx-auto">
						<div className="flex flex-col w-1/2 mr-20">
							<Disclosure>
								{({ open }) => (
									<>
										<Disclosure.Button className="flex w-full justify-between rounded-lg bg-mainBlue px-4 py-2 text-left text-lg font-extrabold font-poppins text-white hover:bg-lightBlue focus:outline-none focus-visible:ring focus-visible:ring-lightBlue focus-visible:ring-opacity-75">
											<span>Fall 2021</span>
											<AiOutlineArrowDown
												className={`${
													open ? "rotate-180 transform" : ""
												} h-5 w-5 text-white`}
											/>
										</Disclosure.Button>
										<Disclosure.Panel
											className="px-4 pt-4 pb-2 text-mainGray font-poppins text-lg font-light"
											as="ul"
										>
											<li>CIS 120: Programming Languages and Techniques I</li>
											<li>
												CIS 160: Mathematical Foundations of Computer Science
											</li>
											<li>ECON 001: Introduction to Microeconomics</li>
											<li>MATH 114: Calculus II</li>
											<li>WRIT 016: The Model Minority Myth</li>
										</Disclosure.Panel>
									</>
								)}
							</Disclosure>
							<Disclosure as="div" className="mt-2">
								{({ open }) => (
									<>
										<Disclosure.Button className="flex w-full justify-between rounded-lg bg-mainBlue px-4 py-2 text-left text-lg font-extrabold font-poppins text-white hover:bg-lightBlue focus:outline-none focus-visible:ring focus-visible:ring-lightBlue focus-visible:ring-opacity-75">
											<span>Spring 2022</span>
											<AiOutlineArrowDown
												className={`${
													open ? "rotate-180 transform" : ""
												} h-5 w-5 text-white`}
											/>
										</Disclosure.Button>
										<Disclosure.Panel
											className="px-4 pt-4 pb-2 text-mainGray font-poppins text-lg font-light"
											as="ul"
										>
											<li>
												CIS 121: Programming Languages and Techniques II (Data
												Structures and Algorithms)
											</li>
											<li>ECON 002: Introduction to Macroeconomics</li>
											<li>MATH 240: Calculus III</li>
											<li>MGMT 101: Introduction to Management</li>
											<li>
												NETS 150: Market and Social Systems on the Internet
											</li>
										</Disclosure.Panel>
									</>
								)}
							</Disclosure>
							<Disclosure as="div" className="mt-2">
								{({ open }) => (
									<>
										<Disclosure.Button className="flex w-full justify-between rounded-lg bg-mainBlue px-4 py-2 text-left text-lg font-extrabold font-poppins text-white hover:bg-lightBlue focus:outline-none focus-visible:ring focus-visible:ring-lightBlue focus-visible:ring-opacity-75">
											<span>Fall 2022</span>
											<AiOutlineArrowDown
												className={`${
													open ? "rotate-180 transform" : ""
												} h-5 w-5 text-white`}
											/>
										</Disclosure.Button>
										<Disclosure.Panel
											className="px-4 pt-4 pb-2 text-mainGray font-poppins text-lg font-light"
											as="ul"
										>
											<li>BEPP 2500: Managerial Economics</li>
											<li>CIS 2620: Automata, Computability, and Complexity</li>
											<li>NETS 2120: Scalable and Cloud Computing</li>
											<li>
												PHYS 0150: Principles of Physics I: Mechanics and Wave
												Motion
											</li>
											<li>STAT 4300: Probability Theory</li>
										</Disclosure.Panel>
									</>
								)}
							</Disclosure>
							<Disclosure as="div" defaultOpen="true" className="mt-2">
								{({ open }) => (
									<>
										<Disclosure.Button className="flex w-full justify-between rounded-lg bg-mainBlue px-4 py-2 text-left text-lg font-extrabold font-poppins text-white hover:bg-lightBlue focus:outline-none focus-visible:ring focus-visible:ring-lightBlue focus-visible:ring-opacity-75">
											<span>Fall 2023</span>
											<AiOutlineArrowDown
												className={`${
													open ? "rotate-180 transform" : ""
												} h-5 w-5 text-white`}
											/>
										</Disclosure.Button>
										<Disclosure.Panel
											className="px-4 pt-4 pb-2 text-mainGray font-poppins text-lg font-light"
											as="ul"
										>
											<li>ACCT 1010: Accounting and Financial Reporting</li>
											<li>CIS 2400: Introduction to Computer Systems</li>
											<li>CIS 4500: Database and Information Systems</li>
											<li>EAS 2030: Engineering Ethics</li>
											<li>FNCE 1000: Corporate Finance</li>
											<li>STAT 4310: Statistical Inference</li>
											<li>WH 2010: Business Communication for Impact</li>
										</Disclosure.Panel>
									</>
								)}
							</Disclosure>
						</div>
						<div className="flex flex-col">
							<div className="rounded-2xl border border-zinc-100 p-6 dark:border-zinc-700/40">
								<h2 className="flex text-sm font-bold text-mainBlack font-poppins">
									<svg
										viewBox="0 0 24 24"
										fill="none"
										stroke-width="1.5"
										stroke-linecap="round"
										stroke-linejoin="round"
										aria-hidden="true"
										class="h-6 w-6 flex-none"
									>
										<path
											d="M2.75 9.75a3 3 0 0 1 3-3h12.5a3 3 0 0 1 3 3v8.5a3 3 0 0 1-3 3H5.75a3 3 0 0 1-3-3v-8.5Z"
											class="fill-zinc-100 stroke-zinc-400 dark:fill-zinc-100/10 dark:stroke-zinc-500"
										></path>
										<path
											d="M3 14.25h6.249c.484 0 .952-.002 1.316.319l.777.682a.996.996 0 0 0 1.316 0l.777-.682c.364-.32.832-.319 1.316-.319H21M8.75 6.5V4.75a2 2 0 0 1 2-2h2.5a2 2 0 0 1 2 2V6.5"
											class="stroke-zinc-400 dark:stroke-zinc-500"
										></path>
									</svg>
									<span className="ml-4 mt-0.5 tracking-normal">Work</span>
								</h2>
								<ol className="mt-6 space-y-4">
									<li className="flex gap-4">
										<div className="relative mt-1 flex h-10 w-10 flex-none items-center justify-center rounded-full shadow-md shadow-zinc-800/5 ring-1 ring-zinc-900/5 dark:border dark:border-zinc-700/50 dark:bg-zinc-800 dark:ring-0">
											<Image
												src={accenture}
												width="32"
												height="32"
												alt="Headshot"
											/>
										</div>
										<dl className="flex flex-auto flex-wrap gap-x-2">
											<dt className="sr-only">Company</dt>
											<dd className="w-full flex-none text-sm font-poppins font-medium text-mainBlack dark:text-zinc-100">
												Accenture
											</dd>
											<dt className="sr-only">Role</dt>
											<dd className="text-xs font-poppins text-mainGray font-light dark:text-zinc-400">
												Incoming Tech Summer Analyst Intern
											</dd>
											<dt className="sr-only">Date</dt>
											<dd
												className="ml-auto text-xs font-poppins text-mainGray font-light dark:text-zinc-500"
												aria-label="2019 until Present"
											>
												<time datetime="2023">June 2023</time>{" "}
												<span aria-hidden="true">—</span>{" "}
												<time datetime="2023">August 2023</time>
											</dd>
										</dl>
									</li>
									<li className="flex gap-4">
										<div className="relative mt-1 flex h-10 w-10 flex-none items-center justify-center rounded-full shadow-md shadow-zinc-800/5 ring-1 ring-zinc-900/5 dark:border dark:border-zinc-700/50 dark:bg-zinc-800 dark:ring-0">
											<Image
												src={supernow}
												width="32"
												height="32"
												alt="Headshot"
											/>
										</div>
										<dl className="flex flex-auto flex-wrap gap-x-2">
											<dt className="sr-only">Company</dt>
											<dd className="w-full flex-none text-sm font-poppins font-medium text-mainBlack dark:text-zinc-100">
												Supernow
											</dd>
											<dt className="sr-only">Role</dt>
											<dd className="text-xs font-poppins text-mainGray font-light dark:text-zinc-400">
												Data Analyst and Software Developer Intern
											</dd>
											<dt className="sr-only">Date</dt>
											<dd
												className="ml-auto text-xs font-poppins text-mainGray font-light dark:text-zinc-500"
												aria-label="2019 until Present"
											>
												<time datetime="2023">July 2022</time>{" "}
												<span aria-hidden="true">—</span>{" "}
												<time datetime="2023">August 2022</time>
											</dd>
										</dl>
									</li>
									<li className="flex gap-4">
										<div className="relative mt-1 flex h-10 w-10 flex-none items-center justify-center rounded-full shadow-md shadow-zinc-800/5 ring-1 ring-zinc-900/5 dark:border dark:border-zinc-700/50 dark:bg-zinc-800 dark:ring-0">
											<Image
												src={firstround}
												width="32"
												height="32"
												alt="Headshot"
											/>
										</div>
										<dl className="flex flex-auto flex-wrap gap-x-2">
											<dt className="sr-only">Company</dt>
											<dd className="w-full flex-none text-sm font-poppins font-medium text-mainBlack dark:text-zinc-100">
												First Round Capital
											</dd>
											<dt className="sr-only">Role</dt>
											<dd className="text-xs font-poppins text-mainGray font-light dark:text-zinc-400">
												Investment Analyst and Software Developer Intern
											</dd>
											<dt className="sr-only">Date</dt>
											<dd
												className="ml-auto text-xs font-poppins text-mainGray font-light dark:text-zinc-500"
												aria-label="2019 until Present"
											>
												<time datetime="2023">June 2022</time>{" "}
												<span aria-hidden="true">—</span>{" "}
												<time datetime="2023">August 2022</time>
											</dd>
										</dl>
									</li>
									<li className="flex gap-4">
										<div className="relative mt-1 flex h-10 w-10 flex-none items-center justify-center rounded-full shadow-md shadow-zinc-800/5 ring-1 ring-zinc-900/5 dark:border dark:border-zinc-700/50 dark:bg-zinc-800 dark:ring-0">
											<Image
												src={seaswellness}
												width="32"
												height="32"
												alt="Headshot"
											/>
										</div>
										<dl className="flex flex-auto flex-wrap gap-x-2">
											<dt className="sr-only">Company</dt>
											<dd className="w-full flex-none text-sm font-poppins font-medium text-mainBlack dark:text-zinc-100">
												SEAS Wellness @ Penn
											</dd>
											<dt className="sr-only">Role</dt>
											<dd className="text-xs font-poppins text-mainGray font-light dark:text-zinc-400">
												Front-End Web Developer Intern
											</dd>
											<dt className="sr-only">Date</dt>
											<dd
												className="ml-auto text-xs font-poppins text-mainGray font-light dark:text-zinc-500"
												aria-label="2019 until Present"
											>
												<time datetime="2023">January 2022</time>{" "}
												<span aria-hidden="true">—</span>{" "}
												<time datetime="2023">February 2022</time>
											</dd>
										</dl>
									</li>
								</ol>
							</div>
						</div>
					</div>
				</section>
			</main>
		</div>
	);
}
